name: Welcome to the party
on: 
  workflow_dispatch:
jobs:
  say_hello:
    name: "Lets great the user"
    runs-on: ubuntu:latest 
    steps:
       - run: echo "Hello madafaca"
       - uses: actions/checkout@v3
       - run: cat ./github/workflows/list.txt
         name : display content of list.txt
       - run: echo "I am step 4"